version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: treasure_hunt_db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: treasure_hunt_db
    ports:
      - 3307:3306
    volumes:
      - player_score:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  player_score: